version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/sergiu
    steps:
      - checkout
      - run:
          name: Install AWS CLI 
          command: |
            pip install awscli
      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id $ACCESS_KEY_ID
            aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
            aws configure set default.region eu-west-1
      - deploy:
          name: Deploy to S3 Static Website Hosting
          command: |
            aws s3 cp index.html s3://$S3_BUCKET_NAME/index.html

