version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    working_directory: ~/sergiu
    steps:
      - checkout
      
      - run:
          name: Copy artifacts
          command: |
            cp index.html /tmp/index.html
            cp .circleci/test-s3-config.py /tmp/test-s3-config.py
      - store_artifacts:
          path: /tmp/index.html
      - store_artifacts:
          path: /tmp/test-s3-config.py
      - store_artifacts:
          path: /tmp/selenium-test-ui.py
      - persist_to_workspace:
                root: /tmp
                paths:
                  - index.html
                  - test-s3-config.py
                  - selenium-test-ui.py

  test-ui:
    docker:
      - image: circleci/python:latest
    working_directory: ~/test
    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: Install PyTest and Selenium
          command: |
            pip install pytest
            pip install selenium
      - run:
          name: Run Selenium 
          command: |
            pytest /tmp/selenium-test-ui.py --verbose --capture=no
      

  deploy-s3:
    docker:
      - image: circleci/python:latest
    working_directory: ~/deploy
    steps:
      - attach_workspace:
          at: /tmp

      - run:
          name: Install AWS CLI 
          command: |
            pip install awscli
            pip install boto3
      - run:
          name: Configure AWS Credentials
          command: |
            aws configure set aws_access_key_id $ACCESS_KEY_ID
            aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
            aws configure set default.region eu-west-1
      - run:
          name: Test S3 Configuration
          command: |
            python /tmp/test-s3-config.py
      - run:
          name: Deploy to S3 Static Website Hosting
          command: |
            aws s3 cp /tmp/index.html s3://$S3_BUCKET_NAME/index.html
      
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-s3:
          requires:
            - build
