# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("http://circleci-sergiu-raduleae.s3-website-eu-west-1.amazonaws.com/")
    self.driver.set_window_size(1084, 688)
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.XPATH, "//p[contains(.,\'Sergiu\')]").click()
    self.driver.close()
